import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const WantedSans = localFont({
  src: "../font/WantedSansVariable.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${WantedSans.className}`}>{children}</body>
    </html>
  );
}
